name: React Project Workflow
description: "Checks and runs tests for react project"
  
inputs:
  # Path input is only required if building a project with front and backends

  path:
    required: False
    description: "Path to project root"
    default: .

  nodeVersion:
    required: False
    description: "Node version to use"
    default: 14.17.0

runs:
  using: composite

  steps:
    - uses: actions/checkout@v2
    - name: Setup Node ${{ inputs.nodeVersion }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: "yarn"
    - name: Cache
      uses: actions/cache@v2
      with:
        path: "**/node_modules"
        key: v0-${{ hashFiles('${{ inputs.path }}/yarn.lock') }}

    - name: Install Dependencies
      shell: bash
      run: |-
        cd ${{ inputs.path }}
        yarn install --frozen-lockfile
    
    - name: Lint
      shell: bash
      run: |-
        cd ${{ inputs.path }}
        yarn lint
    
    - name: Test
      shell: bash
      run: |-
        cd ${{ inputs.path }}
        yarn test
    - name: Upload Code Coverage
      shell: bash
      run: |-
        ROOT=$(pwd)
        cd ${{ inputs.path }}
        yarn run codecov -p $ROOT -F frtype=local,src=/tmp/.buildx-cacheontend
# container:
#   image: node:${{ inputs.nodeVersion }}