name: Django Project Workflow
on:
  workflow_call:
    inputs:
      # Mandatory inputs
      projectName:
        required: true
        type: string
      imageName:
        required: TRUE
        type: string
      githubRef:
        required: true
        type: string
      # Optional finetuning inputs
      defaultBranch:
        required: False
        type: string
        default: master
      path:
        required: False
        type: string
        default: .
      skipDjangoCheck: # NOTE: Use with CAUTION!
        required: False
        type: boolean
        default: false
      pythonVersion:
        required: False
        type: string
        default: 3.8-buster
      # Linting config
      flake:
        required: False
        type: boolean
        default: True
      black:
        required: False
        type: boolean
        default: True
jobs:
  django-check:
    name: Django Check
    runs-on: ubuntu-latest
    if: ${{ !inputs.skipDjangoCheck }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: v0-${{ hashFiles('${{ inputs.path }}/Pipfile.lock') }}
      - name: Install Dependencies
        run: |-
          cd ${{ inputs.path }}
          pip install pipenv
          pipenv install --deploy --dev
      - name: Lint (flake8)
        run: |-
          cd ${{ inputs.path }}
          pipenv run flake8 .
        if: ${{ inputs.flake }}
      - name: Lint (black)
        run: |-
          cd ${{ inputs.path }}
          pipenv run black --check .
        if: ${{ inputs.black }}
      - name: Test (run in parallel)
        run: |-
          cd ${{ inputs.path }}
          pipenv run coverage run --concurrency=multiprocessing manage.py test --settings=${{ inputs.projectName }}.settings.ci --parallel
          pipenv run coverage combine
      - name: Upload Code Coverage
        run: |-
          ROOT=$(pwd)
          cd ${{ inputs.path }}
          pipenv run codecov --root $ROOT --flags ${{ inputs.path }}
    container:
      image: python:${{ inputs.pythonVersion }}
    env:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
        options: "--health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5"
  publish-backend:
    name: Publish backend
    runs-on: ubuntu-latest
    needs: django-check
    if: |
      always() &&
      (needs.django-check.result == 'success' || needs.django-check.result == 'skipped')
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-publish-backend
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build/Publish
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.path }}
          file: ${{ inputs.path }}/Dockerfile
          push: ${{ inputs.githubRef == 'refs/heads/${{ inputs.defaultBranch }}' }}
          cache-from: type=local,src=/tmp/.buildx-cache,type=registry,ref=pennlabs/${{ inputs.imageName }}:latest
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: pennlabs/${{ inputs.imageName }}:latest,pennlabs/${{ inputs.imageName }}:${{ github.sha }}
