name: Django Project Workflow
on:
  workflow_call:
    inputs:
      # Mandatory inputs
      projectName:
        required: true
        type: string
      # Optional finetuning inputs
      path:
        required: False
        type: string
        default: .
      skipDjangoCheck: # NOTE: Use with CAUTION!
        required: False
        type: boolean
        default: false
      pythonVersion:
        required: False
        type: string
        default: 3.8-buster
      # Linting config
      flake:
        required: False
        type: boolean
        default: True
      black:
        required: False
        type: boolean
        default: True
      # Dependency manager config
      dependencyManager:
        required: False
        description: "Dependency manager to use (e.g., pipenv, poetry)"
        default: 'pipenv'
jobs:
  django-check:
    name: Django Check
    runs-on: ubuntu-latest
    if: ${{ !inputs.skipDjangoCheck }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: v0-${{ hashFiles('${{ inputs.path }}/Pipfile.lock') }}
      - name: Install Dependencies
        run: |-
          cd ${{ inputs.path }}
          pip install pipenv
          pipenv install --deploy --dev
        if: ${{ inputs.dependencyManager == 'pipenv' }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        if: ${{ inputs.dependencyManager == 'poetry' }}
      - name: Install Dependencies (poetry)
        run: poetry install --no-root
        if: ${{ inputs.dependencyManager == 'poetry' }}
      - name: Lint (flake8)
        run: |-
          cd ${{ inputs.path }}
          ${{ inputs.dependencyManager }} run flake8 .
        if: ${{ inputs.flake }}
      - name: Lint (black)
        run: |-
          cd ${{ inputs.path }}
          ${{ inputs.dependencyManager }} run black --check .
        if: ${{ inputs.black }}
      - name: Test (run in parallel)
        run: |-
          cd ${{ inputs.path }}
          ${{ inputs.dependencyManager }} run coverage run --concurrency=multiprocessing manage.py test --settings=${{ inputs.projectName }}.settings.ci --parallel
          ${{ inputs.dependencyManager }} run coverage combine
    container:
      image: python:${{ inputs.pythonVersion }}
    env:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
        options: "--health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5"
