name: Deployment Workflow
on:
  workflow_call:
    inputs:
      # Mandatory inputs
      projectName:
        required: true
        type: string
      dockerImageBaseName:
        required: true
        type: string
      # Optional finetuning inputs
      defaultBranch:
        required: False
        type: string
        default: master
      deployTag:
        required: False
        type: string
        default: ${{ github.sha }}
      skipChecks: # NOTE: Use with CAUTION!
        required: False
        type: boolean
        default: false
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      GH_AWS_ACCESS_KEY_ID:
        required: true
      GH_AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  django:
    name: Django
    uses: pennlabs/shared-actions/.github/workflows/django.yaml@main
    with:
      projectName: ${{ inputs.projectName }}
      imageName: "${{ inputs.dockerImageBaseName }}-backend"
      defaultBranch: ${{ inputs.defaultBranch }}
      skipDjangoCheck: ${{ inputs.skipChecks }}
      githubRef: ${{ github.ref }}
      path: backend
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  react:
    name: React
    uses: pennlabs/shared-actions/.github/workflows/react.yaml@main
    with:
      imageName: "${{ inputs.dockerImageBaseName }}-frontend"
      defaultBranch: ${{ inputs.defaultBranch }}
      skipReactCheck: ${{ inputs.skipChecks }}
      githubRef: ${{ github.ref }}
      path: frontend
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  deployment:
    name: Deploy
    uses: pennlabs/shared-actions/.github/workflows/deployment.yaml@main
    with:
      githubRef: ${{ github.ref }}
      defaultBranch: ${{ inputs.defaultBranch }}
      deployTag: ${{ inputs.deployTag }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      GH_AWS_ACCESS_KEY_ID: ${{ secrets.GH_AWS_ACCESS_KEY_ID }}
      GH_AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_AWS_SECRET_ACCESS_KEY }}
    needs:
      - react
      - django
