name: React Project Workflow
on:
  workflow_call:
    inputs:
      path:
        required: False
        type: string
        default: .
      nodeVersion:
        required: False
        type: string
        default: "14"
      dependencyManager:
        required: False
        type: string
        description: "Dependency manager to use (e.g. yarn, bun)"
        default: "yarn"
jobs:
  react-check:
    name: React Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache (yarn)
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: v0-${{ hashFiles('${{ inputs.path }}/yarn.lock') }}
        if: ${{ inputs.dependencyManager == 'yarn' }}
      - name: Cache (bun)
        uses: actions/cache@v2
        with:
          path: |-
            **/node_modules
            **/.bun
          key: v0-${{ hashFiles('${{ inputs.path }}/bun.lockb') }}
        if: ${{ inputs.dependencyManager == 'bun' }}
      - name: Install Dependencies
        run: |-
          cd ${{ inputs.path }}
          ${{ inputs.dependencyManager }} install --frozen-lockfile
      - name: Lint
        run: |-
          cd ${{ inputs.path }}
          ${{ inputs.dependencyManager }} lint
      - name: Test
        run: |-
          cd ${{ inputs.path }}
          ${{ inputs.dependencyManager }} run test
      - name: Upload Code Coverage
        run: |-
          ROOT=$(pwd)
          cd ${{ inputs.path }}
          ${{ inputs.dependencyManager }} run codecov -p $ROOT -F frtype=local,src=/tmp/.buildx-cacheontend
    container:
      image: node:${{ inputs.nodeVersion }}