name: React Project Workflow
on:
  workflow_call:
    inputs:
      # Mandatory inputs
      imageName:
        required: true
        type: string
      githubRef:
        required: true
        type: string
      gitSha:
        required: true
        type: string
      # Optional finetuning inputs
      path:
        required: false
        type: string
        default: .
      dockerfile:
        required: false
        type: string
        default: Dockerfile
      skipReactCheck: # NOTE: Use with CAUTION!
        required: false
        type: boolean
        default: false
      nodeVersion:
        required: false
        type: string
        default: 14
      skipCodecov:
        required: false
        type: boolean
        default: false
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  react-check:
    name: React Check
    runs-on: ubuntu-latest
    if: ${{ !inputs.skipReactCheck }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: v0-${{ hashFiles('${{ inputs.path }}/yarn.lock') }}
      - name: Install Dependencies
        run: |-
          cd ${{ inputs.path }}
          yarn install --frozen-lockfile
      - name: Lint
        run: |-
          cd ${{ inputs.path }}
          yarn lint
      - name: Test
        run: |-
          cd ${{ inputs.path }}
          yarn test
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v4
        if: ${{ !inputs.skipCodecov }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ${{ inputs.path }}
          fail_ci_if_error: true
          name: codecov-umbrella
          verbose: true
    container:
      image: node:${{ inputs.nodeVersion }}
  publish-frontend:
    name: Publish frontend
    runs-on: ubuntu-latest
    needs: react-check
    if: |
      always() &&
      (needs.react-check.result == 'success' || needs.react-check.result == 'skipped')
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-publish-frontend
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build/Publish
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.path }}
          file: ${{ inputs.path }}/${{ inputs.dockerfile }}
          push: ${{ inputs.githubRef == 'master' }}
          cache-from: type=local,src=/tmp/.buildx-cache,type=registry,ref=pennlabs/${{ inputs.imageName }}:latest
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: pennlabs/${{ inputs.imageName }}:latest,pennlabs/${{ inputs.imageName }}:${{ inputs.gitSha }}
